package com.chenboda01.bcompassv1;

import android.app.*;import android.os.*;import android.graphics.*;import android.hardware.*;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity implements SensorEventListener{
 SensorManager sm;Sensor rot,acc;TextView deg,dir,level,status;Dial dial;float az=0,pitch=0,roll=0;
 public void onCreate(Bundle b){super.onCreate(b);sm=(SensorManager)getSystemService(SENSOR_SERVICE);rot=sm.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR);acc=sm.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER);root.setPadding(20,20,20,20);root.setBackgroundColor(Color.rgb(7,19,30));TextView title=txt("B-Compass V1",30,Color.WHITE);deg=txt("0°",54,Color.rgb(80,255,157));dir=txt("N",32,Color.WHITE);level=txt("Level: 0°, 0°",18,Color.WHITE);status=txt("Move phone in a figure-8 to calibrate.",14,Color.LTGRAY);dial=new Dial(this);root.addView(title);root.addView(deg);root.addView(dir);root.addView(dial,new LinearLayout.LayoutParams(-1,0,1));root.addView(level);root.addView(status);setContentView(root);} 
 TextView txt(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER);t.setPadding(4,8,4,8);return t;}
 protected void onResume(){super.onResume();if(rot!=null)sm.registerListener(this,rot,SensorManager.SENSOR_DELAY_UI);if(acc!=null)sm.registerListener(this,acc,SensorManager.SENSOR_DELAY_UI);if(rot==null)status.setText("Compass sensor missing on this phone.");}
 protected void onPause(){super.onPause();sm.unregisterListener(this);} 
 public void onAccuracyChanged(Sensor s,int a){}
 public void onSensorChanged(SensorEvent e){if(e.sensor.getType()==Sensor.TYPE_ROTATION_VECTOR){float[] r=new float[9],o=new float[3];SensorManager.getRotationMatrixFromVector(r,e.values);SensorManager.getOrientation(r,o);az=(float)Math.toDegrees(o[0]);if(az<0)az+=360;deg.setText(Math.round(az)+"°");dir.setText(card(az));dial.invalidate();}else if(e.sensor.getType()==Sensor.TYPE_ACCELEROMETER){float x=e.values[0],y=e.values[1],z=e.values[2];pitch=(float)Math.toDegrees(Math.atan2(x,Math.sqrt(y*y+z*z)));roll=(float)Math.toDegrees(Math.atan2(y,z));level.setText("Level: "+Math.round(pitch)+"°, "+Math.round(roll)+"°");}}
 String card(float a){String[] d={"N","NE","E","SE","S","SW","W","NW","N"};return d[(int)Math.round(a/45f)];}
 public class Dial extends View{Paint p=new Paint(1);public Dial(Activity c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();float cx=w/2f,cy=h/2f,r=Math.min(w,h)*.38f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(8);p.setColor(Color.rgb(32,56,74));c.drawCircle(cx,cy,r,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(42);p.setColor(Color.WHITE);c.drawText("N",cx,cy-r+50,p);c.drawText("S",cx,cy+r-20,p);c.drawText("E",cx+r-30,cy+15,p);c.drawText("W",cx-r+30,cy+15,p);c.save();c.rotate(-az,cx,cy);p.setColor(Color.rgb(80,255,157));Path path=new Path();path.moveTo(cx,cy-r+20);path.lineTo(cx-28,cy);path.lineTo(cx+28,cy);path.close();c.drawPath(path,p);c.restore();}}
}
